### ISSUE TITLE
support for a6100

### ISSUE THREAD

**Issue by Yazzy611** [ma1co/OpenMemories-Framework#33]
Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices
No devices found. Ensure your camera is connected.

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Model:              ILCE-6100
Product code:       0032851025
Serial number:      06176973
Firmware version:   1.00
Lens:               Model 0x12a08019 (Firmware 1.09)

Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 74, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 239, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 35, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

**Comment by rohhn** [comment]
You have to connect the camera with the USB Connection setting set to `Auto` or `MTP`, I think that should resolve the issue.
